# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64, arm]
        goarm: [n.a.]
        include:
          - os: linux
            arch: arm
            goarm: 5
          - os: linux
            arch: arm
            goarm: 6
          - os: linux
            arch: arm
            goarm: 7
        exclude:
          - os: darwin
            arch: arm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment ${{ matrix.os }} ${{ matrix.arch }}
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Build executable
        run: go build -ldflags "-X main.version=${{  github.ref_name }}" -o ./dist/go-dht
        if: matrix.goarm != 'n.a.'
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.goarm }}

      - name: Build executable
        run: go build -ldflags "-X main.version=${{  github.ref_name }}" -o ./dist/go-dht
        if: matrix.goarm == 'n.a.'
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: compress executable (arm)
        if: matrix.goarm != 'n.a.'
        run: |
          cd ./dist
          chmod +x go-dht
          zip go-dht-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.goarm }}.zip go-dht

      - name: compress executable
        if: matrix.goarm == 'n.a.'
        run: |
          cd ./dist
          chmod +x go-dht
          zip go-dht-${{ matrix.os }}-${{ matrix.arch }}.zip go-dht

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          repository: wasilak/go-dht
          files: |
            dist/go-dht*.zip
